name: Deploy to EC2

on:
  push:
    branches:
      - caizin-insync-V2.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/Caizin-HR-Bot
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart caizin-hr-bot
